### ISSUE TITLE
Package conflict in Anaconda3

### ISSUE THREAD

**Issue by svaksha** [ViDA-NYU/reprozip#157]
On Ubuntu-14.04 LTS 32-bit, installing `reprozip` in Anaconda3 leads to a package conflict with python 3.4:

```
स्वक्ष@ilak:~/anaconda3$ conda install -c https://conda.anaconda.org/vida-nyu reprounzip
Fetching package metadata: ......
Solving package specifications: ..........
Error: Unsatisfiable package specifications.
Generating hint: 
[      COMPLETE      ]|#######################################################################################################################################| 100%


Hint: the following packages conflict with each other:
  - reprounzip
  - python 3.4*

Use 'conda info reprounzip' etc. to see the dependencies for each package.

स्वक्ष@ilak:~/anaconda3$ conda info reprounzip
Fetching package metadata: ....
Error: No packages found in current linux-32 channels matching: reprounzip
```

Thanks.

**Comment by remram44** [comment]
Indeed, the Conda package lists a dependency on "python", and it looks like this means it needs Python 2.7. Anaconda environments can only have one Python version, so this conflicts with Python 3.4.

I don't know if there is a way to create "universal" packages, in the worse case I can make two versions since conda has a proper dependency solver. In the meantime, you can create a Python 2 environment to install reprounzip in (or install reprounzip using `pip`, or `conda skeleton`).

Thanks for reporting this, I am looking into it!

**Comment by svaksha** [comment]
On Sun, Oct 25, 2015 at 5:17 AM, Remi Rampin <notifications@github.com> wrote:
>
> Indeed, the Conda package lists a dependency on "python", and it looks like this means it needs Python 2.7. Anaconda environments can only have one Python version, so this conflicts with Python 3.4.
>
> I don't know if there is a way to create "universal" packages, in the worse case I can make two versions since conda has a proper dependency solver. In the meantime, you can create a Python 2 environment to install reprounzip in (or install reprounzip using pip, or conda skeleton).
>

IIRC, the anaconda installation for 2.x and 3.4 have been split?
Earlier I could create a distinct 3.x version with a simple flag but
now the installers have been split I suppose. I suppose it makes sense
as the dep management will be easier, so for your usecase, you may
have to create a new version for 3.x versions.


> Thanks for reporting this, I am looking into it!

Thanks for writing this!


SVAKSHA ॥  http://about.me/svaksha  ॥

**Comment by remram44** [comment]
The Anaconda installation is not actually split, in that you can use Conda to change your version of Python; but every other package that is part of Anaconda would conflict. You can however create environments with a different version of Python.

It looks like Conda packages are only linked against one version of Python, that is chosen with the `--python` flag of `conda build`; even changing the dependencies in `meta.yaml` doesn't help since the directory name depends on the version (e.g. `lib/python3.5/site-package/`). I'm going to change my build scripts to build packages for both `2.7` and `3.2+`.

**Comment by remram44** [comment]
I have built packages for Python 3.5 for all platforms (except Windows, which is Python 3.4). You should be able to install and use ReproZip in Anaconda environments with Python 3.

Let me know if something goes wrong.

**Comment by svaksha** [comment]
On Tue, Oct 27, 2015 at 12:47 AM, Remi Rampin <notifications@github.com> wrote:
>
> I have built packages for Python 3.5 for all platforms (except Windows, which is Python 3.4). You should be able to install and use ReproZip in Anaconda environments with Python 3.
>

Thank you Remi. I shall try them out soon.

SVAKSHA ॥  http://about.me/svaksha  ॥
