### ISSUE TITLE
Input/Output tracing for newer version of Ubuntu

### ISSUE THREAD

**Issue by BinalModi** [ViDA-NYU/reprozip#317]
For the new version of Ubuntu, the input/output files are not put down in input/output section of the config file.
PS - Also tested with digits-sklearn-opencv and digits-sklearn with the current version of reprozip

**Comment by remram44** [comment]
I can't seem to reproduce this.

You might be hitting one of [the many heuristics](https://github.com/ViDA-NYU/reprozip/blob/a47290f781e08338c8615c65d1e228bc383de772/reprozip/reprozip/tracer/trace.py#L193-L204), for example [those directories are ignored](https://github.com/ViDA-NYU/reprozip/blob/a47290f781e08338c8615c65d1e228bc383de772/reprozip/reprozip/tracer/linux_pkgs.py#L30-L31).

@fchirigati do you have more info?

**Comment by remram44** [comment]
Ok we figured it out! This is because that laptop uses reprozip from the Ubuntu package repository, which only has ReproZip 1.0.10 (it is actually [packaged by Debian](https://tracker.debian.org/pkg/reprozip), maybe we can get them to update?)

The bug we run into is #293. We checked that using reprozip 1.0.14 (from pip) everything works fine on that machine.
